### ISSUE TITLE
Error on loading the data

### ISSUE THREAD

**Issue by liquidcarbon** [MannLabs/alphatims#154]
**Describe the bug**
Following the `nbs/tutorial.ipynb`, pointing to my data.  On loading the data, a warning is thrown:
`WARNING: AlphaTims version none was used to initialize ..., while the current version of AlphaTims is 0.3.0.`

Followed by this error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
./alphatims/alphatims/bruker.py in convert_slice_key_to_int_array(data, key, dimension)
   2543     try:
-> 2544         iter(key)
   2545     except TypeError:

TypeError: 'slice' object is not iterable

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_547/2072517597.py in <module>
      1 reload()
      2 bruker_d_folder_name = '.../bruker_data.d/'
----> 3 data = alphatims.bruker.TimsTOF(bruker_d_folder_name)

./alphatims/alphatims/bruker.py in __init__(self, bruker_d_folder_name, mz_estimation_from_frame, mobility_estimation_from_frame, slice_as_dataframe, use_calibrated_mz_values_as_default)
    956         )
    957         # Precompile
--> 958         self[0, "raw"]
    959         logging.info(f"Succesfully imported data from {bruker_d_folder_name}")
    960 

./alphatims/alphatims/bruker.py in __getitem__(self, keys)
   1426         else:
   1427             as_dataframe = self.slice_as_dataframe
-> 1428         parsed_keys = parse_keys(self, keys)
   1429         raw_indices = filter_indices(
   1430             frame_slices=parsed_keys["frame_indices"],

./alphatims/alphatims/bruker.py in parse_keys(data, keys)
   2436             dimension_slices[
   2437                 dimension
-> 2438             ] = convert_slice_key_to_int_array(
   2439                 data,
   2440                 keys[i] if (i < len(keys)) else slice(None),

./alphatims/alphatims/bruker.py in convert_slice_key_to_int_array(data, key, dimension)
   2559                 if not isinstance(start, (np.inexact, float)):
   2560                     raise ValueError
-> 2561                 start = data.convert_to_indices(
   2562                     start,
   2563                     return_type=dimension

./alphatims/alphatims/bruker.py in convert_to_indices(self, values, return_frame_indices, return_scan_indices, return_tof_indices, side, return_type)
   1389             return np.searchsorted(self.rt_values, values, side)
   1390         elif return_type == "scan_indices":
-> 1391             return self.scan_max_index - np.searchsorted(
   1392                 self.mobility_values[::-1],
   1393                 values,

./alphatims/alphatims/bruker.py in scan_max_index(self)
    763     def scan_max_index(self):
    764         """: int : The maximum scan index."""
--> 765         return self._scan_max_index
    766 
    767     @property

AttributeError: 'TimsTOF' object has no attribute '_scan_max_index'
```

**To Reproduce**
1. Created clean conda env `conda env create -n alphatims -f misc/conda_development_environment.yaml`
2. Opened the tutorial notebook file in the new env, using `nb_conda_kernels`
3. Tried to point the notebook to my data

**Version (please complete the following information):**
2021-10-25 09:21:27> Platform information:
2021-10-25 09:21:27> system        - Linux
2021-10-25 09:21:27> release       - 5.10.16.3-microsoft-standard-WSL2
2021-10-25 09:21:27> version       - #1 SMP Fri Apr 2 22:23:49 UTC 2021
2021-10-25 09:21:27> machine       - x86_64
2021-10-25 09:21:27> processor     - x86_64
2021-10-25 09:21:27> cpu count     - 8
2021-10-25 09:21:27> cpu frequency - 2803.21 Mhz
2021-10-25 09:21:27> ram           - 24.2/24.8 Gb (available/total)
2021-10-25 09:21:27> 
2021-10-25 09:21:27> Python information:
2021-10-25 09:21:27> alphatims  - 0.3.0
2021-10-25 09:21:27> bokeh      - 2.2.3
2021-10-25 09:21:27> click      - 8.0.3
2021-10-25 09:21:27> datashader - 0.12.1
2021-10-25 09:21:27> h5py       - 3.5.0
2021-10-25 09:21:27> hvplot     - 0.7.1
2021-10-25 09:21:27> numba      - 0.54.1
2021-10-25 09:21:27> pandas     - 1.3.4
2021-10-25 09:21:27> psutil     - 5.8.0
2021-10-25 09:21:27> python     - 3.8.12
2021-10-25 09:21:27> python-lzf - 0.2.4
2021-10-25 09:21:27> pyzstd     - 0.15.0
2021-10-25 09:21:27> selenium   - 3.141.0
2021-10-25 09:21:27> tqdm       - 4.62.3
2021-10-25 09:21:27>

**Comment by swillems** [comment]
Dear @liquidcarbon. I have released version 0.3.1, which should provide the error message. If there still remain issues, let me know and we can reopen this issue and reinvestigate...
