### ISSUE TITLE
Calibration

### ISSUE THREAD

**Issue by swillems** [MannLabs/alphatims#25]
Calibration of mobility and mz over the gradient is not performed yet. This can be done with e.g. lockmasses such as 622.028960. Moreover, initial mapping of indices to mz and mobility values sometimes has a huge error

**Comment by tomthun** [comment]
Does this mean that exported tof .d data to mgf are still uncalibrated? Will this feature be added at some point? Do we also have the ion mobility information in the mgf format?

**Comment by tomthun** [comment]
Also apparently numpy now requires that you specify np.int as np.int32 or np.int64. Thus an error in bruker.py at line 1985 from the alphatims package arose which could be solved when specified as np.int64.

**Comment by sander-willems-bruker** [comment]
Dear @tomthun, this calibration unfortunately is not being actively developed. Their is nowadays an option `use_calibrated_mz_values_as_default` that tries to tackle this issue somewhat, but it remains highly experimental and I advise to use this with care!
With respect to the numpy issue, this is solved in the latest release
